// Generated by https://quicktype.io

export interface IAdminLoginResponse {
    id: string;
    nombre: string;
    apellidoPaterno: string;
    apellidoMaterno: string;
    email: string;
    username: string;
}

// Generated by https://quicktype.io

export interface IAdminLoginRequest {
    username: string;
    pass: string;
}
